// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Y-Qh603KqoUFHf9iskGgcTXLHF5NyPQ',
    appId: '1:667742117269:web:63d42f60f1c1191056aa9c',
    messagingSenderId: '667742117269',
    projectId: 'e-learning-application-7c9a6',
    authDomain: 'e-learning-application-7c9a6.firebaseapp.com',
    storageBucket: 'e-learning-application-7c9a6.appspot.com',
    measurementId: 'G-P0KPS8PB70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCADSr5Rq9zd3avrG6LOiI7lzTs1mA11f0',
    appId: '1:667742117269:android:7d19e633df12fac856aa9c',
    messagingSenderId: '667742117269',
    projectId: 'e-learning-application-7c9a6',
    storageBucket: 'e-learning-application-7c9a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5WOlWojgtEFP7gNNyhzMtsbq4mWSOEs8',
    appId: '1:667742117269:ios:99530c1a532393c956aa9c',
    messagingSenderId: '667742117269',
    projectId: 'e-learning-application-7c9a6',
    storageBucket: 'e-learning-application-7c9a6.appspot.com',
    iosBundleId: 'com.example.eLearningApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5WOlWojgtEFP7gNNyhzMtsbq4mWSOEs8',
    appId: '1:667742117269:ios:99530c1a532393c956aa9c',
    messagingSenderId: '667742117269',
    projectId: 'e-learning-application-7c9a6',
    storageBucket: 'e-learning-application-7c9a6.appspot.com',
    iosBundleId: 'com.example.eLearningApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Y-Qh603KqoUFHf9iskGgcTXLHF5NyPQ',
    appId: '1:667742117269:web:63d42f60f1c1191056aa9c',
    messagingSenderId: '667742117269',
    projectId: 'e-learning-application-7c9a6',
    authDomain: 'e-learning-application-7c9a6.firebaseapp.com',
    storageBucket: 'e-learning-application-7c9a6.appspot.com',
    measurementId: 'G-P0KPS8PB70',
  );

}